### ISSUE TITLE
Style for accessibility screen reader text on rtl site adds unwanted horizontal scroll bar

### ISSUE THREAD

**Issue by nirrosenbaum** [copyblogger/genesis-sample#18]
Steps to recreate:
A fresh WP install with language set to one of the RTL languages (Hebrew, Arabic).
Using the genesis sample theme with the necessary rtl css rule overrides in the rtl.css file (that is loaded by WP by default, for RTL sites).
Accessibility option is enabled (either by the add theme support or by using the Genesis Accessibility plugin).
Added a simple page widget to the primary sidebar with the "read More" option turned on.
An horizontal scroll bar appears at the bottom of the browser.

Investigation:
Using the Chrome DevTools -> Inspect Element on the "read more" link on the primary sidebar.
The screen-reader-text class is the one causing the issue.
Adding right:0 to this class, resolves the issue.

My assumption:
In this class (screen-reader-text), the position is set to absolute.
Using position:absolute without the right (or left) rule confuses the browser...

**Comment by dreamwhisper** [comment]
Still looking into this, but I'm currently not able to replicate the scrollbar when using WP RTL language settings at this time.

(I can if eNews is installed an active since that has separate `screenread` CSS that does cause the scrollbar.)

**Comment by nickcernis** [comment]
I'm also unable to reproduce this so far with the current beta branch.

<img width="1095" alt="screen shot on 2018-03-20 at 19_34_08" src="https://user-images.githubusercontent.com/647669/37773042-c981d0d6-2ddc-11e8-8ce1-70d69f9fbe65.png">

I suspect styling has diverged enough since September 2015 that this is no longer an issue. Happy to reopen and revisit if we see further reports, though.
