### ISSUE TITLE
Update sample.xml for WooCommerce pages

### ISSUE THREAD

**Issue by seothemes** [copyblogger/genesis-sample#62]

**Comment by dreamwhisper** [comment]
We've specifically kept WooCommerce pages and products out of our main theme XML files due to feedback and questions we've had through support. (Especially, products because the post type doesn't exist.)

If there's a compelling reason to add them, I'm open to discuss it. Otherwise, I think we can close this.

**Comment by seothemes** [comment]
Not really, thought you guys might have missed it that's all.
