### ISSUE TITLE
page-landing.php file name

### ISSUE THREAD

**Issue by srikat** [copyblogger/genesis-sample#77]
The name of the landing pages template, `page-landing.php` might be a source of confusion as typically one would expect it to be a template that will automatically be used by a Page whose slug is `landing` per the WordPress [template hierarchy](https://developer.wordpress.org/themes/template-files-section/page-template-files/#page-templates-within-the-template-hierarchy).

Wouldn't `template-landing.php` be a better file name for it?

**Comment by dreamwhisper** [comment]
@nickcernis For now, thoughts on leaving it as page_landing.php? That naming convention is still specifically noted in the codex and also follows what we do in Genesis for templates. Consistency may be better than worrying about what our IDE is telling us.

**Comment by nickcernis** [comment]
@dreamwhisper For me it's worth changing to avoid the, “is this a page template or a custom one?” issue that Sridhar mentioned — I agree that it can be confusing otherwise.

We do have an established convention in Genesis as you say, and the codex still uses a `page-` prefix in [their example](https://developer.wordpress.org/themes/template-files-section/page-template-files/#identifying-a-page-template), but:

1. I'm not sure that Genesis can responsibly change page template names or locations; it would break all child themes that have template overrides as well as unsetting the page template for themes where the Genesis version's in use. If we delay this change until Genesis adopts a new convention (or drops all page templates), my guess is we'll be waiting a while.

2. Lead WP devs have previously recommended [template naming conventions](https://nacin.com/2012/03/29/page-templates-in-subdirectories-new-in-wordpress-3-4/) that contradict the Codex, and I think they are clearer than the `page-` convention.

3. Leaving it as `page_landing.php` throws a phpcs warning (for the underscore, because phpcs is mean). If we're going to change it to a `-` in this release, we may as well rename or move it too if it makes things more clear.

4. Genesis has no page_landing.php that we're overriding so it's safe to move it in Sample.

Personally I would move `page-landing.php` to `/page-templates/landing.php` (where it will work automatically without further configuration and give us somewhere to put other templates), but the `template-landing.php` that Sridhar proposes is also fine.

Overrides for Genesis page templates would then be the only ones that lived in the child theme root.

Beyond the thoughts above I don't have strong feelings about this, though, and can revert the existing change from `page-landing.php` to `page_landing.php` and add an exclude to the phpcs config if needed:

```xml
<rule ref="WordPress.Files.FileName.UnderscoresNotAllowed">
    <exclude-pattern>page_landing.php</exclude-pattern>
</rule>
```

**Comment by dreamwhisper** [comment]
> phpcs is mean

It totally is - I've noticed 😉 

We've never really had any confusion about the template naming. The Codex does mention using page_ here: https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-custom-page-templates-for-global-use but doesn't say `Don't do that`.

But, let me throw this out there ... I've long thought that our `page_landing.php` should be an additional layout and NOT a template. The same thing could be accomplished as a layout without the UX confusion that our current template has. 

For example, you can select the template, but you could still try to select a layout with a sidebar. That doesn't work the way our template is built. If it were a layout instead, the UX confusion wouldn't be there.

**Comment by nickcernis** [comment]
> But, let me throw this out there ... I've long thought that our page_landing.php should be an additional layout and NOT a template. The same thing could be accomplished as a layout without the UX confusion that our current template has.

I really like that idea and it could fit in better with Gutenberg too (because the layout options are more discoverable and clearer than the template drop-down).
