### ISSUE TITLE
Large logo centered with fixed header

### ISSUE THREAD

**Issue by mjsdiaz** [copyblogger/genesis-sample#94]
Allowing a custom width for the logo is a really nice! And centering the logo and menu for logo widths greater than 600px works great. 

But if the logo is that wide, there's a good chance that it will be "rather tall" too, and in that case the fixed header could be really tall, and not allow for much content.

I'd like to suggest that the fixed header be removed for the large centered logos. 

In output.php, 
`	.site-header {
		position: relative;
        }`
could be added to the `@media only screen and (min-width: 960px) {`
section

**Comment by nickcernis** [comment]
Thanks for testing this and for the feedback, Marcy — I like the idea.

We could even set a logo height at which the sticky header should become non-sticky.

For example, this will remove the sticky header if the logo height is 200px or more (assuming the logo image width is greater than the selected max-width value, which we could optionally test for):

```php
$logo_height = ( $logo_max_width / genesis_sample_custom_logo_ratio() );

if ( $logo_height >= 200 ) {
	$css .= '
	.site-header {
		position: relative;
	}
	';
}
```

Where `genesis_sample_custom_logo_ratio()` is defined as:

```php
/**
 * The ratio of the custom logo (width/height).
 * Gives x in: x * height = width.
 * A ratio below one means the logo is taller than it is wide.
 *
 * @since 2.4.0
 *
 * @return float|null The ratio of width:height or null.
 */
function genesis_sample_custom_logo_ratio() {
	$logo = wp_get_attachment_image_src( get_theme_mod( 'custom_logo' ), false, false );
	list($_, $width, $height) = $logo;

	if ( $width && $height ) {
		return (float) ( $width / $height );
	}
}
```

That way, if someone has a skyscraper logo, the header won't be sticky and cover up their content as you rightly point out, even if it's otherwise narrower than 600px.

**Comment by mjsdiaz** [comment]
Oh, this is even better, Nick! That will really help all the DIY people.

**Comment by nickcernis** [comment]
Tested and confirmed fixed header is made static if logo is tall.

Commits are part of https://github.com/copyblogger/genesis-sample/pull/93 in branch beta-logo-size.

https://github.com/copyblogger/genesis-sample/pull/93/commits/d9913824e37cf69fe970fc0d65f85d23630f5769

Thanks again for taking an interest and for your feedback, Marcy!
